name: Run Collector Script

on:
  workflow_dispatch: # allows manual run
  schedule:
    - cron: "0 8 * * *" # runs every day at 08:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"

    - name: Install dependencies
      run: pip install requests

    - name: Run collector script
      env:
        WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK }}
      run: python collector.py

    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: ioc-results
        path: "*.csv"
